name: CI
on: push

jobs:
  ci:
    strategy:
      matrix:
        servers: [ubuntu-latest, macos-latest, self-hosted]
        python-version: ["3.8"]
      fail-fast: false
    runs-on: ${{matrix.servers}}
    steps:
      - name: Checkout repo
        run: |
          rm -rf ${{github.event.repository.name}}
          git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}
          git -C "${{github.workspace}}/${{github.event.repository.name}}" checkout ${{github.ref}}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Python unittest
        run: |
          python -m venv venv
          source venv/bin/activate
          cd ${{github.event.repository.name}}
          pip install -r requirements.txt
          pre-commit run -a
          python -m unittest discover -v
      - name: Cleanup
        run: |
          rm -rf venv
          rm -rf ${{github.event.repository.name}}
